SRCDIR = ..

# Test programs to compile, and a list of sources for each.
# To add a new test, put its name on the PROGS list
# and then add a name_SRC line that lists its source files.
PROGS = cat cmp cp crrm echo exit fio fio2 halt hang hex-dump \
  ls mcat mcp mkdir pwd rm shell \
	bubsort insult lineup matmult recursor parrot telseek \
	zombie big_array big_stack debug

# Should work from project 2 onward.
cat_SRC = cat.c
cmp_SRC = cmp.c
cp_SRC = cp.c
crrm_SRC = crrm.c
echo_SRC = echo.c
exit_SRC = exit.c
fio_SRC = fio.c
fio2_SRC = fio2.c
halt_SRC = halt.c
hang_SRC = hang.c
hex-dump_SRC = hex-dump.c
insult_SRC = insult.c
lineup_SRC = lineup.c
ls_SRC = ls.c
recursor_SRC = recursor.c
rm_SRC = rm.c
parrot_SRC = parrot.c
telseek_SRC = telseek.c
zombie_SRC = zombie.c

# Should work in project 3; also in project 4 if VM is included.
big_array_SRC = big_array.c
big_stack_SRC = big_stack.c
bubsort_SRC = bubsort.c
matmult_SRC = matmult.c
mcat_SRC = mcat.c
mcp_SRC = mcp.c

# Should work in project 4.
mkdir_SRC = mkdir.c
pwd_SRC = pwd.c
shell_SRC = shell.c

# debug helper
debug_SRC = debug.c

include $(SRCDIR)/Make.config
include $(SRCDIR)/Makefile.userprog
